# Generated by Django 4.0.4 on 2022-09-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveBigIntegerField()),
                ('street_no', models.CharField(max_length=50)),
                ('colony', models.CharField(choices=[('idupulapaya', 'idupulapaya'), ('vempalli', 'vempalli'), ('kadiri', 'kadiri'), ('marripaadu', 'marripaadu'), ('rajampet', 'rajampet'), ('rajupalem', 'rajupalem'), ('kamalapuram', 'kamalapuram'), ('jammalamadugu', 'jammalamadugu'), ('pendlimarri', 'pendlimarri'), ('mylavaram', 'mylavaram'), ('duvuur', 'duvvur')], max_length=50)),
                ('name_of_pub', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('no_of_pages', models.PositiveIntegerField(default=1)),
                ('no_of_copies', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('black and white', 'balck and white'), ('colur', 'colour')], default='colour', max_length=20)),
                ('paper', models.CharField(choices=[('a4', 'a4'), ('pic', 'pic'), ('book', 'book')], default='', max_length=10)),
                ('sides', models.CharField(choices=[('one side', 'one side'), ('two side', 'two side')], default='', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
